### PR TITLE
Parkings as services

### PR DESCRIPTION
**Pull request by Anaethelion**
Remove parking feature from treks and add it to services.
Add data migration.
Add cache for buildout deps.
Add fix to prevent error on service add if no path exists in database.

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
It means that we dont localize parkings anymore when we create a trek ?
And what about labels on Parking highlight ?

parking

**Comment by Anaethelion** [comment]
Hello Camille,

This has been made as per request from Cevennes's requirements, i thought that was agreed beforehand.
If need be, i can make it so the two functionalities work along each others.

The goal was to have the parkings in geotrek-rando in a nice popup for visitors.
Let met know what you thinks !

**Comment by camillemonchicourt** [comment]
OK I'll talk about it with them today to see the consequences.

**Comment by camillemonchicourt** [comment]
OK, I talked with PNC and they also dont understand. 
It is very important to associate ONE parking with each trek. It cant work automatically with a buffer. 
V1 system was perfect.

**Pull request closed without merging**
