### PR TITLE
Publication workflow (fixes #1018)

### LINKED ISSUE #1018: Trek published field should have a workflow
* https://django-xworkflows.readthedocs.org
* Draf > Review > Published
* Ref #1003 

Check compatibilty with modeltranslation to keep publication status by lang

### PR DESCRIPTION
**Pull request by gutard**

### CODE REVIEW

**Comment by leplatrem** [comment]
:+1:

**Comment by camillemonchicourt** [comment]
How is the WORKFLOW working ? 
Will it impact GEOTREK functionalities ? As we dont need it at PNE.

**Comment by gutard** [comment]
No big impact if you don't use it. Just a new checkbox "Waiting for publication" you can ignore. And a new permissions "can publish ..." to grant to users.

**Comment by camillemonchicourt** [comment]
OK thanks for the details.

**Pull request merged**
